[server]
headless = false 
address = "127.0.0.1"
port = 8501
enableXsrfProtection = true
maxUploadSize = 1

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false